name: Build and Push Auto-Versioned Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # --- Read and increment version ---
    - name: Increment version
      id: bump
      run: |
        VERSION_FILE=version.txt
        CURRENT_VERSION=$(cat $VERSION_FILE)
        echo "Current version: $CURRENT_VERSION"

        IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
        NEW_VERSION="$major.$minor.$((patch + 1))"
        echo "$NEW_VERSION" > $VERSION_FILE
        echo "New version: $NEW_VERSION"

        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

    # --- Commit updated version.txt ---
    - name: Commit updated version
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add version.txt
        git commit -m "Bump version to ${{ steps.bump.outputs.version }}"
        git push

    # --- Log in to GHCR ---
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # --- Build and push Docker image ---
    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/hello-ghcr:latest
          ghcr.io/${{ github.repository_owner }}/hello-ghcr:${{ steps.bump.outputs.version }}

    # --- Print pushed version ---
    - name: Show pushed image tag
      run: echo "Pushed version: ${{ steps.bump.outputs.version }}"